# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.6.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: Travis
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 13.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: 'Management of Return Merchandise Authorization (RMA) in Odoo :
  product return, warranty control, product exchange, product refund...'
repo_name: RMA (Return Merchandise Authorization)
repo_slug: rma
repo_website: https://github.com/OCA/rma
travis_apt_packages: []
travis_apt_sources: []
