# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.7.0
_src_path: gh:oca/oca-addons-repo-template
ci: Travis
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: 'TODO: add repo description.'
repo_name: rma
repo_slug: rma
repo_website: https://github.com/OCA/rma
travis_apt_packages: []
travis_apt_sources: []

