[project]
name = "odoo-addons-oca-rma"
version = "19.0.20260921.0"
dependencies = [
    "odoo-addon-product_warranty==19.0.*",
    "odoo-addon-rma==19.0.*",
    "odoo-addon-rma_sale==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
